# Generated by Django 2.2.2 on 2019-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
    ]
